[package]
name = "rusty_math"
version = "0.1.2"
edition = "2021"
author = "Kshitij Makwana"
description = "rusty_math is a collection of mathematical functions implemented in Rust"
repository = "https://github.com/kjmakwana/rusty_math"
license-file = "LICENSE"

[dependencies]
